{{- range $appName, $appConfigFull := .Values }}
{{- if typeIs "map[string]interface {}" $appConfigFull }}
{{- $appSecrets := $appConfigFull.secrets }}
{{- if and $appSecrets $appSecrets.data (gt (len $appSecrets.data) 0) }}
{{- $target := index $appSecrets "target" | default dict }}
{{- $hasTargetName := and $target $target.name }}
{{- $esName := "" }}
{{- if $hasTargetName }}
{{- $esName = $target.name }}
{{- else }}
{{- $esName = printf "%s-%s-secrets%s" $.Values.projectName $appName (include "external-secrets.k8sSecretSuffix" $) }}
{{- end }}
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: {{ $esName }}
  namespace: {{ $appConfigFull.namespace | default "default" }}
  annotations:
    argocd.argoproj.io/sync-wave: {{ $appConfigFull.syncWave | default "-2" | quote }}
spec:
  refreshInterval: {{ $appSecrets.refreshInterval | default "1h" }}
  secretStoreRef:
    name: {{ $.Values.secretStoreName | default "aws-secrets-manager" }}
    kind: ClusterSecretStore
  target:
    name: {{ $esName }}
    creationPolicy: Owner
  data:
    {{- range $item := $appSecrets.data }}
    - secretKey: {{ $item.secretKey }}
      remoteRef:
        key: {{ $item.remoteRef.key | default $appSecrets.remoteKey }}
        property: {{ $item.remoteRef.property }}
    {{- end }}
{{- end }}
{{- end }}
{{- end }}
