{{- range $appName, $appConfig := .Values.appsByEnv }}
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: {{ $.Values.env }}-{{ $.Values.name }}-{{ $appName }}-app
  namespace: argocd
  labels:
    project: {{ $.Values.name }}
    env: {{ $.Values.env }}
    component: {{ $appName }}
  annotations:
    argocd.argoproj.io/sync-wave: {{ quote $appConfig.syncWave }}
spec:
  project: {{ $.Values.project }}
  source:
    repoURL: {{ $.Values.repoURL }}
    targetRevision: main
    path: template
    helm:
      releaseName: {{ $appName }}
      valueFiles:
        - ../app/{{ $appConfig.profile }}.yaml
        - ../env/{{ $.Values.env }}.yaml
        - ../config/base/config.yaml
        - ../config/env/{{ $.Values.env }}.yaml
      parameters:
        - name: currentService
          value: {{ $appName }}
        - name: nameOverride
          value: {{ $appName }}
        - name: fullnameOverride
          value: {{ $appName }}
  destination:
    name: {{ $.Values.cluster }}
    namespace: {{ $appConfig.namespace }}-{{ $.Values.env }}
  syncPolicy:
    {{- if eq (toString $.Values.automated) "true" }}
    automated:
      prune: true
      selfHeal: true
    {{- end }}
    retry:
      limit: 3
      backoff:
        duration: 30s
        maxDuration: 5m
        factor: 2
    syncOptions:
      - CreateNamespace=true
  ignoreDifferences:
    - group: argoproj.io
      kind: Rollout
      jsonPointers:
        - /spec/replicas
    - group: apps
      kind: Deployment
      jsonPointers:
        - /spec/replicas
    - group: apps
      kind: StatefulSet
      jsonPointers:
        - /spec/replicas
    - group: cilium.io
      kind: CiliumNetworkPolicy
      jqPathExpressions:
        - .status
    - group: traefik.io
      kind: IngressRoute
      jqPathExpressions:
        - .status
    - group: traefik.io
      kind: TraefikService
      jqPathExpressions:
        - .status
        - .spec.weighted.services[].weight
    - group: networking.k8s.io
      kind: Ingress
      jqPathExpressions:
        - .status
{{- end }}